[project]
name = "parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.63.0",
    "fastapi[standard]>=0.121.3",
    "ray>=2.52.0",
    "uvicorn>=0.38.0",
]
